version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - backend
    links:
      - backend
  backend:
    container_name: backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env